### ISSUE TITLE
"Class app does not exist" with "yii-base-api"

### ISSUE THREAD

**Issue by marcelodeandrade** [yiisoft/yii-project-template#23]
### What steps will reproduce the problem?
Follow the installation instructions 

1. composer create-project --prefer-dist --stability=dev yiisoft/yii-project-template myapp
2. cd myapp
3. composer require yiisoft/yii-base-api
4. vendor/bin/yii serve -p 8081

### What is the expected result?
Run new application

### What do you get instead?
```

PHP Fatal error:  Uncaught ReflectionException: Class app does not exist in /home/marcelo/Documents/myapp/vendor/yiisoft/di/src/AbstractContainer.php:415
Stack trace:
#0 /home/marcelo/Documents/myapp/vendor/yiisoft/di/src/AbstractContainer.php(415): ReflectionClass->__construct('app')
#1 /home/marcelo/Documents/myapp/vendor/yiisoft/di/src/AbstractContainer.php(340): yii\di\AbstractContainer->getDependencies('app')
#2 /home/marcelo/Documents/myapp/vendor/yiisoft/di/src/AbstractContainer.php(186): yii\di\AbstractContainer->buildFromConfig('app', Array)
#3 /home/marcelo/Documents/myapp/vendor/yiisoft/di/src/AbstractContainer.php(131): yii\di\AbstractContainer->buildWithDefinition('app', Array, Array)
#4 /home/marcelo/Documents/myapp/vendor/yiisoft/di/src/Container.php(55): yii\di\AbstractContainer->build('app')
#5 /home/marcelo/Documents/myapp/public/index.php(14): yii\di\Container->get('app')
#6 /home/marcelo/Documents/myapp/public/index.php(15): {closure}()
#7 {main}

Next yii\di\exceptions\InvalidConfigException: Failed to ins in /home/marcelo/Documents/myapp/vendor/yiisoft/di/src/AbstractContainer.php on line 417
[Fri Dec 14 16:56:05 2018] ::1:35302 [500]: / - Uncaught ReflectionException: Class app does not exist in /home/marcelo/Documents/myapp/vendor/yiisoft/di/src/AbstractContainer.php:415
Stack trace:
#0 /home/marcelo/Documents/myapp/vendor/yiisoft/di/src/AbstractContainer.php(415): ReflectionClass->__construct('app')
#1 /home/marcelo/Documents/myapp/vendor/yiisoft/di/src/AbstractContainer.php(340): yii\di\AbstractContainer->getDependencies('app')
#2 /home/marcelo/Documents/myapp/vendor/yiisoft/di/src/AbstractContainer.php(186): yii\di\AbstractContainer->buildFromConfig('app', Array)
#3 /home/marcelo/Documents/myapp/vendor/yiisoft/di/src/AbstractContainer.php(131): yii\di\AbstractContainer->buildWithDefinition('app', Array, Array)
#4 /home/marcelo/Documents/myapp/vendor/yiisoft/di/src/Container.php(55): yii\di\AbstractContainer->build('app')
#5 /home/marcelo/Documents/myapp/public/index.php(14): yii\di\Container->get('app')
#6 /home/marcelo/Documents/myapp/public/index.php(15): {closure}()
#7 {main}

Next yii\di\exceptions\InvalidConfigException: Failed to ins in /home/marcelo/Documents/myapp/vendor/yiisoft/di/src/AbstractContainer.php on line 417
```

**Comment by prawee** [comment]
same me

**Comment by samdark** [comment]
That's expected. Check yiisoft/yii-demo for now...
