### ISSUE TITLE
TypeError: Return value of yii\helpers\BaseYii::getFactory() must be an instance of yii\di\FactoryInterface, instance of yii\di\Factory

### ISSUE THREAD

**Issue by schmunk42** [yiisoft/yii-project-template#3]
I've setup and installed the application with Docker, when requesting the index page I get the following error:

```
php-fpm_1  | [21-Aug-2018 17:34:03] WARNING: [pool www] child 11 said into stderr: "NOTICE: PHP message: An Error occurred while handling another error:"
php-fpm_1  | [21-Aug-2018 17:34:03] WARNING: [pool www] child 11 said into stderr: "TypeError: Return value of yii\helpers\BaseYii::getFactory() must be an instance of yii\di\FactoryInterface, instance of yii\di\Factory returned in /app/vendor/yiisoft/core/src/helpers/BaseYii.php:102"
php-fpm_1  | [21-Aug-2018 17:34:03] WARNING: [pool www] child 11 said into stderr: "Stack trace:"
php-fpm_1  | [21-Aug-2018 17:34:03] WARNING: [pool www] child 11 said into stderr: "#0 /app/vendor/yiisoft/core/src/helpers/BaseYii.php(69): yii\helpers\BaseYii::getFactory(Object(yii\di\Container))"
php-fpm_1  | [21-Aug-2018 17:34:03] WARNING: [pool www] child 11 said into stderr: "#1 /app/vendor/yiisoft/core/src/base/Component.php(774): yii\helpers\BaseYii::createObject(Array)"
php-fpm_1  | [21-Aug-2018 17:34:03] WARNING: [pool www] child 11 said into stderr: "#2 /app/vendor/yiisoft/core/src/base/Component.php(759): yii\base\Component->attachBehaviorInternal('access', Array)"
php-fpm_1  | [21-Aug-2018 17:34:03] WARNING: [pool www] child 11 said into stderr: "#3 /app/vendor/yiisoft/core/src/base/Component.php(752): yii\base\Component->attachBehaviorsInternal(Array)"
php-fpm_1  | [21-Aug-2018 17:34:03] WARNING: [pool www] child 11 said into stderr: "#4 /app/vendor/yiisoft/core/src/base/Component.php(613): yii\base\Component->ensureBehaviors()"
php-fpm_1  | [21-Aug-2018 17:34:03] WARNING: [pool www] child 11 said into stderr: "#5 /app/vendor/yiisoft/core/src/base/Controller.php(276): yii\base\Component->trigger(Object(yii\base\ActionEvent))"
php-fpm_1  | [21-Aug-2018 17:34:03] WARNING: [pool www] child 11 said into stderr: "#6 /app/vendor/yiisoft/yii-web/src/Controller.php(165): yii\base\Controller->beforeActio..."
```

Might be a issue in the core though.

**Comment by hiqsol** [comment]
Looks like you have old `yiisoft/di` package...
In latest versions `yii\di\Factory` implements `yii\di\FactoryInterface` so should not raise such error.
Try `composer update`

**Comment by schmunk42** [comment]
Just ran an update, same error...

Output of `composer show`:

```
bower-asset/bootstrap              v4.1.3            
doctrine/instantiator              dev-master 870a62d A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                     dev-master c0970c7 Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
egulias/email-validator            2.1.5              A library for validating emails against several RFCs
hiqdev/composer-config-plugin      dev-master 7e6e4fa Composer plugin for config assembling
myclabs/deep-copy                  1.x-dev 3e01bda    Create deep copies (clones) of your objects
npm-asset/jquery                   3.2.1             
npm-asset/punycode                 1.3.2             
npm-asset/typeahead.js             0.11.1            
phar-io/manifest                   dev-master 7761fca Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                    2.0.1              Library for handling version information and constraints
phpdocumentor/reflection-common    1.0.1              Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock  4.3.0              With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is emb...
phpdocumentor/type-resolver        0.4.0             
phpspec/php-diff                   dev-master 0464787 A comprehensive library for generating differences between two hashable objects (strings or arrays).
phpspec/prophecy                   dev-master 4ba436b Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage          dev-master dfb0bf3 Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator          dev-master cecbc68 FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template          1.2.1              Simple template engine.
phpunit/php-timer                  dev-master 9ef9968 Utility class for timing
phpunit/php-token-stream           dev-master 711ca0c Wrapper around PHP's tokenizer extension.
phpunit/phpunit                    dev-master 5a789fe The PHP Unit Testing framework.
psr/container                      1.0.0              Common Container Interface (PHP FIG PSR-11)
psr/http-message                   dev-master f6561bf Common interface for HTTP messages
psr/log                            dev-master 3490ba5 Common interface for logging libraries
psr/simple-cache                   dev-master 408d5ea Common interfaces for simple caching
sebastian/code-unit-reverse-lookup dev-master 22f5f5f Looks up which function or method a line of code belongs to
sebastian/comparator               dev-master 5de4fc1 Provides the functionality to compare PHP values for equality
sebastian/diff                     dev-master 366541b Diff implementation
sebastian/environment              dev-master 32c5cba Provides functionality to handle HHVM/PHP environments
sebastian/exporter                 dev-master c8c4f19 Provides the functionality to export PHP variables for visualization
sebastian/global-state             dev-master 30367ea Snapshotting of global state
sebastian/object-enumerator        dev-master 06d95dc Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector         dev-master 7707193 Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context        dev-master dbe1869 Provides functionality to recursively process PHP variables
sebastian/resource-operations      dev-master 0f9911f Provides a list of PHP built-in functions that operate on resources
sebastian/version                  2.0.1              Library that helps with managing the version number of Git-hosted PHP projects
swiftmailer/swiftmailer            dev-master ae9a3d0 Swiftmailer, free feature-rich PHP mailer
theseer/tokenizer                  1.1.0              A small library for converting tokenized PHP source code into XML and potentially other formats
vlucas/phpdotenv                   dev-master 8abb4f9 Loads environment variables from `.env` to `getenv()`, `$_ENV` and `$_SERVER` automagically.
webmozart/assert                   dev-master 53927dd Assertions to validate method input/output with nice error messages.
yiisoft/active-record              dev-master a3715c2 Yii ActiveRecord Library
yiisoft/cache                      dev-master 7c20db2 Yii Caching Library
yiisoft/core                       dev-master 7adc4bc Yii Framework Core
yiisoft/db                         dev-master 8cb4f6a Yii DataBase Library
yiisoft/di                         dev-master 294acae Yii DI container
yiisoft/log                        dev-master b8f6813 Yii Logging Library
yiisoft/view                       dev-master cd76f83 Yii View Rendering Library
yiisoft/yii-app                    dev-master 29fb688 Yii Framework Application
yiisoft/yii-bootstrap4             dev-master c245477 The Twitter Bootstrap 4 extension for the Yii framework
yiisoft/yii-captcha                dev-master 10d7325 Yii Framework Captcha widget Extension
yiisoft/yii-console                dev-master 2cd67f7 Yii Framework Console Extension
yiisoft/yii-debug                  dev-master 0690b29 Yii Framework Debugger Extension
yiisoft/yii-gii                    dev-master c3fd54b Yii framework Gii Extension
yiisoft/yii-jquery                 dev-master 05ce284 Yii Framework jQuery Extension
yiisoft/yii-swiftmailer            dev-master 6b6d462 The SwiftMailer integration for the Yii framework
yiisoft/yii-web                    dev-master b47de1d Yii Framework Web Extension
```

**Comment by samdark** [comment]
Was fixed in yiisoft/di
