### ISSUE TITLE
Installation.

### ISSUE THREAD

**Issue by tecnoterabyte** [yiisoft/yii-project-template#4]
Hi. I'm trying to install the template, I know it's in a test state, I follow the steps:

```
composer create-project --prefer-dist --stability=dev yiisoft/yii-app-template myapp
cd myapp
./vendor/bin/yii serve
```

I get the error An internal server error occurred.

How do I run the template in my domain on port 80,

Thks,

**Comment by tecnoterabyte** [comment]
ok I know how to assign the domain:

```
./vendor/bin/yii serve/index example.com:8080

Error:

[Wed Aug 22 15:10:36 2018] An Error occurred while handling another error:
TypeError: Return value of yii\helpers\BaseYii::getFactory() must be an instance of yii\di\FactoryInterface, instance of yii\di\Factory returned in /home/app.cjtterabyte.com/public_html/vendor/yiisoft/core/src/helpers/BaseYii.php:102
Stack trace:
#0 /home/app.cjtterabyte.com/public_html/vendor/yiisoft/core/src/helpers/BaseYii.php(69): yii\helpers\BaseYii::getFactory(Object(yii\di\Container))
#1 /home/app.cjtterabyte.com/public_html/vendor/yiisoft/core/src/base/Component.php(774): yii\helpers\BaseYii::createObject(Array)
#2 /home/app.cjtterabyte.com/public_html/vendor/yiisoft/core/src/base/Component.php(759): yii\base\Component->attachBehaviorInternal('access', Array)
#3 /home/app.cjtterabyte.com/public_html/vendor/yiisoft/core/src/base/Component.php(752): yii\base\Component->attachBehaviorsInternal(Array)
#4 /home/app.cjtterabyte.com/public_html/vendor/yiisoft/core/src/base/Component.php(613): yii\base\Component->ensureBehaviors()
#5 /home/app.cjtterabyte.com/public_html/vendor/yiisoft/core/src/base/Controller.php(276): yii\base\Component->trigger(Object(yii\base\ActionEvent))
#6 /home/app.cjtterabyte.com/public_html/vendor/yiisoft/yii-web/src/Controller.php(165): yii\base\Controller->beforeAction(Object(yii\web\ErrorAction))
#7 /home/app.cjtterabyte.com/public_html/vendor/yiisoft/core/src/base/Controller.php(158): yii\web\Controller->beforeAction(Object(yii\web\ErrorAction))
#8 /home/app.cjtterabyte.com/public_html/vendor/yiisoft/core/src/base/Module.php(542): yii\base\Controller->runAction('error', Array)
#9 /home/app.cjtterabyte.com/public_html/vendor/yiisoft/yii-web/src/ErrorHandler.php(103): yii\base\Module->runAction('site/error')
#10 /home/app.cjtterabyte.com/public_html/vendor/yiisoft/core/src/base/ErrorHandler.php(123): yii\web\ErrorHandler->renderException(Object(TypeError))
#11 [internal function]: yii\base\ErrorHandler->handleException(Object(TypeError))
#12 {main}

```

How can the port be changed ?

**Comment by rustamwin** [comment]
> TypeError: Return value of yii\helpers\BaseYii::getFactory() must be an instance of yii\di\FactoryInterface, instance of yii\di\Factory returned in /home/example.com/public_html/vendor/yiisoft/core/src/helpers/BaseYii.php:102

this is core issue

**Comment by tecnoterabyte** [comment]
On the other hand, it is extraordinary to be able to update yii-app by the composer, what I do not like is this new approach of running a service with a specific port, in the yii3 version in the yii2 repository, it worked without running any separate process, which It is simpler and less load the server since I do not have to have a running process.

**Comment by tecnoterabyte** [comment]
Hi @hiqsol the error is commit 2f19368ceab4829c1a0e054e2720faf64344cfcd,

Thks,

**Comment by SilverFire** [comment]
Fixed in commit https://github.com/yiisoft/di/commit/351502d835d97ab21b4ffd729feb14981aaf06bc

Sorry for the break

**Comment by tecnoterabyte** [comment]
Excelent work @SilverFire no problem

**Comment by hiqsol** [comment]
Everything should work fine now.
