### ISSUE TITLE
Class app does not exist error in public diroctory..

### ISSUE THREAD

**Issue by bilginnet** [yiisoft/yii-project-template#45]
### What steps will reproduce the problem?
I got this error after install in public dir.

Uncaught ReflectionException: Class app does not exist in "..\vendor\yiisoft\factory\src\Resolvers\ClassNameResolver.php:22"
 Stack trace: #0 "..\vendor\yiisoft\factory\src\Resolvers\ClassNameResolver.php(22): ReflectionClass->__construct('app')"

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 3.0.?
| PHP version      | 7.4.0
| Operating system | Windows 10 - xampp

**Comment by samdark** [comment]
Use yiisoft/yii-demo for now.

**Comment by schmunk42** [comment]
I tried to apply the changes from `yii-demo`, but got

```

Fatal error: Uncaught Yiisoft\Factory\Exceptions\NotFoundException: No definition for Psr\Http\Message\ServerRequestFactoryInterface in /app/vendor/yiisoft/di/src/Container.php:152 Stack trace: #0 /app/vendor/yiisoft/di/src/Container.php(130): Yiisoft\Di\Container->buildPrimitive('Psr\\Http\\Messag...', Array) 
#1 /app/vendor/yiisoft/di/src/Container.php(113): Yiisoft\Di\Container->buildInternal('Psr\\Http\\Messag...', Array) 
#2 /app/vendor/yiisoft/di/src/Container.php(79): Yiisoft\Di\Container->build('Psr\\Http\\Messag...', Array) 
#3 /app/vendor/yiisoft/factory/src/Definitions/ClassDefinition.php(31): Yiisoft\Di\Container->get('Psr\\Http\\Messag...') 
#4 /app/vendor/yiisoft/factory/src/Definitions/ArrayBuilder.php(63): Yiisoft\Factory\Definitions\ClassDefinition->resolve(Object(Yiisoft\Di\Container)) 
#5 /app/vendor/yiisoft/factory/src/Definitions/ArrayBuilder.php(47): Yiisoft\Factory\Definitions\ArrayBuilder->resolveDependency(Object(Yiisoft\Di\Container), Object(Yiisoft\Factory\Definitions\ClassDefinition)) 
#6 /app/vendor in /app/vendor/yiisoft/di/src/Container.php on line 152
```
